"use client";

import { useEffect, useState } from "react";
import { ApiError, createJob, getValidation, listTemplates, processJob, uploadPages } from "@/lib/api";
import type { ProcessJobRequest, TemplateSummary, ValidationResult } from "@/lib/types";
import StepIndicator, { type Step } from "@/components/StepIndicator";
import StepHome from "@/components/StepHome";
import StepDownloadTemplate from "@/components/StepDownloadTemplate";
import StepUploadPages from "@/components/StepUploadPages";
import StepProcessing from "@/components/StepProcessing";
import StepCharacterReview from "@/components/StepCharacterReview";
import StepFontPreview from "@/components/StepFontPreview";
import StepDownload from "@/components/StepDownload";

const DEFAULT_METADATA: ProcessJobRequest = {
  family_name: "PersonalFont",
  creator: "PersonalFont",
  version: "1.0",
  description: "A personalized handwriting font generated by PersonalFont.",
};

export default function Page() {
  const [step, setStep] = useState<Step>("home");

  const [templates, setTemplates] = useState<TemplateSummary[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);
  const [templateError, setTemplateError] = useState<string | null>(null);

  const [jobId, setJobId] = useState<string | null>(null);
  const [creatingJob, setCreatingJob] = useState(false);

  const [files, setFiles] = useState<File[]>([]);
  const [metadata, setMetadata] = useState<ProcessJobRequest>(DEFAULT_METADATA);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const [processingError, setProcessingError] = useState<string | null>(null);
  const [validations, setValidations] = useState<ValidationResult[]>([]);

  useEffect(() => {
    listTemplates()
      .then((results) => {
        setTemplates(results);
        setSelectedTemplateId(results[0]?.template_id ?? null);
      })
      .catch((err) => setTemplateError(err instanceof Error ? err.message : "Could not load templates."));
  }, []);

  async function handleContinueFromTemplate() {
    if (!selectedTemplateId) return;
    setCreatingJob(true);
    setTemplateError(null);
    try {
      const status = await createJob(selectedTemplateId);
      setJobId(status.job_id);
      setStep("upload");
    } catch (err) {
      setTemplateError(err instanceof ApiError ? err.message : "Could not start a job.");
    } finally {
      setCreatingJob(false);
    }
  }

  async function handleUploadAndProcess() {
    if (!jobId) return;
    setSubmitting(true);
    setUploadError(null);
    try {
      await uploadPages(jobId, files);
      await processJob(jobId, metadata);
      setStep("processing");
    } catch (err) {
      setUploadError(err instanceof ApiError ? err.message : "Could not upload pages.");
    } finally {
      setSubmitting(false);
    }
  }

  async function handleProcessingCompleted() {
    if (!jobId) return;
    try {
      const results = await getValidation(jobId);
      setValidations(results);
      setStep("review");
    } catch (err) {
      const message =
        err instanceof ApiError ? err.message : "Font finished but validation results couldn't be loaded.";
      setUploadError(message);
      setStep("upload");
    }
  }

  function handleRestart() {
    setStep("home");
    setJobId(null);
    setFiles([]);
    setMetadata(DEFAULT_METADATA);
    setUploadError(null);
    setProcessingError(null);
    setValidations([]);
  }

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-8 px-6 py-12 sm:px-10">
      {step !== "home" && <StepIndicator current={step} />}

      {step === "home" && <StepHome onStart={() => setStep("template")} />}

      {step === "template" && (
        <StepDownloadTemplate
          templates={templates}
          selectedTemplateId={selectedTemplateId}
          onSelectTemplate={setSelectedTemplateId}
          onContinue={handleContinueFromTemplate}
          onBack={() => setStep("home")}
          loading={creatingJob}
          error={templateError}
        />
      )}

      {step === "upload" && jobId && (
        <StepUploadPages
          files={files}
          onFilesChange={setFiles}
          metadata={metadata}
          onMetadataChange={setMetadata}
          onSubmit={handleUploadAndProcess}
          onBack={() => setStep("template")}
          submitting={submitting}
          error={uploadError}
        />
      )}

      {step === "processing" && jobId && (
        <StepProcessing
          jobId={jobId}
          onCompleted={handleProcessingCompleted}
          onFailed={(message) => {
            setProcessingError(message);
            setStep("upload");
            setUploadError(message);
          }}
        />
      )}

      {step === "review" && (
        <StepCharacterReview
          validations={validations}
          onContinue={() => setStep("preview")}
          onBack={() => setStep("upload")}
        />
      )}

      {step === "preview" && jobId && (
        <StepFontPreview jobId={jobId} onContinue={() => setStep("download")} onBack={() => setStep("review")} />
      )}

      {step === "download" && jobId && (
        <StepDownload jobId={jobId} familyName={metadata.family_name} onRestart={handleRestart} />
      )}

      {processingError && step !== "upload" && (
        <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950 dark:text-red-300">
          {processingError}
        </p>
      )}
    </div>
  );
}
