"use client";

import { useEffect, useState } from "react";
import {
  ApiError,
  createFreeformJob,
  createJob,
  getValidation,
  listTemplates,
  processJob,
  uploadPages,
} from "@/lib/api";
import type { ProcessJobRequest, TemplateSummary, ValidationResult } from "@/lib/types";
import StepIndicator, { type Step } from "@/components/StepIndicator";
import StepHome from "@/components/StepHome";
import StepDownloadTemplate from "@/components/StepDownloadTemplate";
import StepUploadPages from "@/components/StepUploadPages";
import StepUploadFreeform from "@/components/StepUploadFreeform";
import StepProcessing from "@/components/StepProcessing";
import StepCharacterReview from "@/components/StepCharacterReview";
import StepRewrite from "@/components/StepRewrite";
import StepFontPreview from "@/components/StepFontPreview";
import StepDownload from "@/components/StepDownload";

const DEFAULT_METADATA: ProcessJobRequest = {
  family_name: "PersonalFont",
  creator: "PersonalFont",
  version: "1.0",
  description: "A personalized handwriting font generated by PersonalFont.",
};

export default function Page() {
  const [step, setStep] = useState<Step>("home");

  const [templates, setTemplates] = useState<TemplateSummary[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);
  const [templateError, setTemplateError] = useState<string | null>(null);

  const [jobId, setJobId] = useState<string | null>(null);
  const [creatingJob, setCreatingJob] = useState(false);
  const [jobIsFreeform, setJobIsFreeform] = useState(false);

  const [files, setFiles] = useState<File[]>([]);
  const [metadata, setMetadata] = useState<ProcessJobRequest>(DEFAULT_METADATA);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const [freeformFile, setFreeformFile] = useState<File | null>(null);
  const [freeformSubmitting, setFreeformSubmitting] = useState(false);
  const [freeformError, setFreeformError] = useState<string | null>(null);

  const [processingError, setProcessingError] = useState<string | null>(null);
  const [validations, setValidations] = useState<ValidationResult[]>([]);

  useEffect(() => {
    listTemplates()
      .then((results) => {
        setTemplates(results);
        setSelectedTemplateId(results[0]?.template_id ?? null);
      })
      .catch((err) => setTemplateError(err instanceof Error ? err.message : "Could not load templates."));
  }, []);

  async function handleContinueFromTemplate() {
    if (!selectedTemplateId) return;
    setCreatingJob(true);
    setTemplateError(null);
    try {
      const status = await createJob(selectedTemplateId);
      setJobId(status.job_id);
      setJobIsFreeform(false);
      setStep("upload");
    } catch (err) {
      setTemplateError(err instanceof ApiError ? err.message : "Could not start a job.");
    } finally {
      setCreatingJob(false);
    }
  }

  async function handleUploadAndProcess() {
    if (!jobId) return;
    setSubmitting(true);
    setUploadError(null);
    try {
      await uploadPages(jobId, files);
      await processJob(jobId, metadata);
      setStep("processing");
    } catch (err) {
      setUploadError(err instanceof ApiError ? err.message : "Could not upload pages.");
    } finally {
      setSubmitting(false);
    }
  }

  async function handleSubmitFreeform() {
    if (!freeformFile) return;
    setFreeformSubmitting(true);
    setFreeformError(null);
    try {
      const status = await createFreeformJob(freeformFile, metadata);
      setJobId(status.job_id);
      setJobIsFreeform(true);
      setStep("freeform-processing");
    } catch (err) {
      setFreeformError(err instanceof ApiError ? err.message : "Could not upload the photo.");
    } finally {
      setFreeformSubmitting(false);
    }
  }

  async function handleProcessingCompleted() {
    if (!jobId) return;
    try {
      const results = await getValidation(jobId);
      setValidations(results);
      setProcessingError(null);
      setStep("review");
    } catch (err) {
      const message =
        err instanceof ApiError ? err.message : "Font finished but validation results couldn't be loaded.";
      setUploadError(message);
      setStep("upload");
    }
  }

  async function handleExcludeProcessingCompleted() {
    if (!jobId) return;
    try {
      const results = await getValidation(jobId);
      setValidations(results);
      setProcessingError(null);
      setStep("preview");
    } catch (err) {
      const message =
        err instanceof ApiError ? err.message : "Font finished but validation results couldn't be loaded.";
      setProcessingError(message);
      setStep("review");
    }
  }

  function handleRestart() {
    setStep("home");
    setJobId(null);
    setJobIsFreeform(false);
    setFiles([]);
    setFreeformFile(null);
    setMetadata(DEFAULT_METADATA);
    setUploadError(null);
    setFreeformError(null);
    setProcessingError(null);
    setValidations([]);
  }

  return (
    <>
      <header className="sticky top-0 z-10 grid grid-cols-[1fr_minmax(0,auto)_1fr] items-center gap-4 border-b border-stone-200 bg-background/95 px-6 py-3 backdrop-blur sm:px-10 dark:border-stone-800">
        <button
          type="button"
          onClick={handleRestart}
          className="justify-self-start text-sm font-semibold tracking-tight text-stone-900 transition-colors hover:text-violet-700 dark:text-stone-50 dark:hover:text-violet-400"
        >
          PersonalFont
        </button>
        {step !== "home" && <StepIndicator current={step} />}
        <div />
      </header>

      <div className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-8 px-6 py-12 sm:px-10">

        {step === "home" && (
          <StepHome onStartTemplate={() => setStep("template")} onStartFreeform={() => setStep("freeform-upload")} />
        )}

        {step === "template" && (
          <StepDownloadTemplate
            templates={templates}
            selectedTemplateId={selectedTemplateId}
            onSelectTemplate={setSelectedTemplateId}
            onContinue={handleContinueFromTemplate}
            onBack={() => setStep("home")}
            loading={creatingJob}
            error={templateError}
          />
        )}

        {step === "upload" && jobId && (
          <StepUploadPages
            files={files}
            onFilesChange={setFiles}
            metadata={metadata}
            onMetadataChange={setMetadata}
            onSubmit={handleUploadAndProcess}
            onBack={() => setStep("template")}
            submitting={submitting}
            error={uploadError}
          />
        )}

        {step === "freeform-upload" && (
          <StepUploadFreeform
            file={freeformFile}
            onFileChange={setFreeformFile}
            metadata={metadata}
            onMetadataChange={setMetadata}
            onSubmit={handleSubmitFreeform}
            onBack={() => setStep("home")}
            submitting={freeformSubmitting}
            error={freeformError}
          />
        )}

        {step === "processing" && jobId && (
          <StepProcessing
            jobId={jobId}
            onCompleted={handleProcessingCompleted}
            onFailed={(message) => {
              setProcessingError(message);
              setUploadError(message);
              setStep("upload");
            }}
          />
        )}

        {step === "freeform-processing" && jobId && (
          <StepProcessing
            jobId={jobId}
            onCompleted={handleProcessingCompleted}
            onFailed={(message) => {
              setProcessingError(message);
              setFreeformError(message);
              setStep("freeform-upload");
            }}
          />
        )}

        {step === "review" && jobId && (
          <StepCharacterReview
            jobId={jobId}
            validations={validations}
            onContinue={() => setStep("preview")}
            onBack={() => setStep(jobIsFreeform ? "freeform-upload" : "upload")}
            onRewrite={() => setStep("rewrite")}
            onExcluded={() => setStep("exclude-processing")}
          />
        )}

        {step === "rewrite" && jobId && (
          <StepRewrite jobId={jobId} onSubmitted={() => setStep("rewrite-processing")} onBack={() => setStep("review")} />
        )}

        {step === "rewrite-processing" && jobId && (
          <StepProcessing
            jobId={jobId}
            onCompleted={handleProcessingCompleted}
            onFailed={(message) => {
              setProcessingError(message);
              setStep("rewrite");
            }}
          />
        )}

        {step === "exclude-processing" && jobId && (
          <StepProcessing
            jobId={jobId}
            onCompleted={handleExcludeProcessingCompleted}
            onFailed={(message) => {
              setProcessingError(message);
              setStep("review");
            }}
          />
        )}

        {step === "preview" && jobId && (
          <StepFontPreview jobId={jobId} onContinue={() => setStep("download")} onBack={() => setStep("review")} />
        )}

        {step === "download" && jobId && (
          <StepDownload jobId={jobId} familyName={metadata.family_name} onRestart={handleRestart} />
        )}

        {processingError && step !== "upload" && step !== "freeform-upload" && (
          <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950 dark:text-red-300">
            {processingError}
          </p>
        )}
      </div>
    </>
  );
}
