"""Stage 13 (spec §13): assemble the final downloadable MyFont.zip —
the TTF, OTF, preview image/PDF, a zip of the individual vector glyphs,
metadata, and a README — from the outputs of every prior stage.

This module only reads already-produced files and writes one zip; it
does not regenerate anything. Font generation, preview rendering, and
this stage stay in their own modules (spec §10's "keep vectorization
separate from font generation" applies by the same logic here).
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from pipeline.font_generation.config import FontMetadata
from pipeline.font_generation.schema import GeneratedFont
from pipeline.packaging.errors import PackagingError
from pipeline.packaging.schema import FontPackage
from pipeline.validation.schema import ValidationResult

README_TEMPLATE = """\
{family_name}
{underline}

Generated by PersonalFont from your own handwriting.
V1 is a deterministic pipeline — nothing in this font was invented by AI.

Contents
--------
{postscript_name}.ttf   TrueType font (install this, or the .otf — not both)
{postscript_name}.otf   OpenType/CFF font
preview.png              Sample rendering of your font
preview.pdf              Sample rendering of your font (print-friendly)
glyphs.zip               Individual vector (SVG) glyphs
metadata.json             Font metadata and character coverage

Installing the font
--------------------
Windows / macOS: double-click the .ttf or .otf file and choose "Install".
Linux: copy the .ttf or .otf into ~/.local/share/fonts, then run: fc-cache -f

Character coverage
-------------------
{valid_count} of {total_count} requested characters were included in this font.
{invalid_note}
"""


def _build_metadata_dict(
    generated_font: GeneratedFont,
    metadata: FontMetadata,
    template_id: str,
    validations: list[ValidationResult],
) -> dict:
    return {
        "family_name": metadata.family_name,
        "style_name": metadata.style_name,
        "version": metadata.version,
        "creator": metadata.creator,
        "description": metadata.description,
        "template_id": template_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "glyph_count": generated_font.glyph_count,
        "valid_characters": sorted(v.character_id for v in validations if v.valid),
        "invalid_characters": sorted(v.character_id for v in validations if not v.valid),
    }


def _build_readme_text(metadata: FontMetadata, validations: list[ValidationResult]) -> str:
    valid_count = sum(1 for v in validations if v.valid)
    total_count = len(validations)
    invalid_count = total_count - valid_count
    invalid_note = (
        f"{invalid_count} character(s) need a clearer rewrite and were left out of this font."
        if invalid_count
        else "Every requested character was included."
    )
    return README_TEMPLATE.format(
        family_name=metadata.family_name,
        underline="=" * len(metadata.family_name),
        postscript_name=metadata.postscript_name,
        valid_count=valid_count,
        total_count=total_count,
        invalid_note=invalid_note,
    )


def _build_glyphs_zip_bytes(svg_dir: Path) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for svg_file in sorted(svg_dir.glob("*.svg")):
            zf.write(svg_file, arcname=svg_file.name)
    return buffer.getvalue()


def build_font_package(
    generated_font: GeneratedFont,
    metadata: FontMetadata,
    template_id: str,
    validations: list[ValidationResult],
    svg_dir: Path,
    preview_png_path: Path,
    preview_pdf_path: Path,
    output_dir: Path,
) -> FontPackage:
    ttf_path = Path(generated_font.ttf_path)
    otf_path = Path(generated_font.otf_path)

    for required_path in (ttf_path, otf_path, preview_png_path, preview_pdf_path):
        if not required_path.is_file():
            raise PackagingError(f"Cannot build the font package: missing input file {required_path}.")

    output_dir.mkdir(parents=True, exist_ok=True)
    zip_path = output_dir / f"{metadata.postscript_name}.zip"

    metadata_json = json.dumps(_build_metadata_dict(generated_font, metadata, template_id, validations), indent=2)
    readme_text = _build_readme_text(metadata, validations)
    glyphs_zip_bytes = _build_glyphs_zip_bytes(svg_dir)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(ttf_path, arcname=f"{metadata.postscript_name}.ttf")
        zf.write(otf_path, arcname=f"{metadata.postscript_name}.otf")
        zf.write(preview_png_path, arcname="preview.png")
        zf.write(preview_pdf_path, arcname="preview.pdf")
        zf.writestr("metadata.json", metadata_json)
        zf.writestr("README.txt", readme_text)
        zf.writestr("glyphs.zip", glyphs_zip_bytes)

    return FontPackage(zip_path=str(zip_path))
