"""Font-level configuration and metadata (spec §11)."""

from __future__ import annotations

from dataclasses import dataclass

from pipeline.normalization.config import NormalizationConfig

# Reuse Phase 7's canvas/baseline numbers rather than a second,
# independently-hardcoded set — the SVG paths this stage consumes were
# drawn in that exact coordinate space (canvas_height px tall, baseline at
# baseline_ratio*canvas_height), so unitsPerEm/ascender/descender must
# stay derived from it, not redefined.
_NORMALIZATION_DEFAULTS = NormalizationConfig()


@dataclass(frozen=True)
class FontGenerationConfig:
    units_per_em: int = _NORMALIZATION_DEFAULTS.canvas_height
    baseline_px: float = round(_NORMALIZATION_DEFAULTS.baseline_ratio * _NORMALIZATION_DEFAULTS.canvas_height)

    # Left and right side bearing applied to every glyph, in font units.
    side_bearing_units: float = 40.0

    # Horizontal margin (each side) of the placeholder ".notdef" box.
    notdef_margin_units: float = 50.0

    @property
    def ascender(self) -> int:
        return round(self.baseline_px)

    @property
    def descender(self) -> int:
        return -round(self.units_per_em - self.baseline_px)


@dataclass(frozen=True)
class FontMetadata:
    family_name: str = "PersonalFont"
    style_name: str = "Regular"
    version: str = "1.0"
    creator: str = "PersonalFont"
    description: str = "A personalized handwriting font generated by PersonalFont."

    @property
    def full_name(self) -> str:
        return f"{self.family_name} {self.style_name}".strip()

    @property
    def postscript_name(self) -> str:
        # PostScript names must be ASCII with no spaces; this is a
        # deliberately simple V1 sanitizer (strip to alphanumerics), not a
        # full Unicode-safe slugifier.
        safe_family = "".join(ch for ch in self.family_name if ch.isalnum()) or "PersonalFont"
        return f"{safe_family}-{self.style_name}"
