"""Request/response models for endpoints not already served by an
existing pipeline-stage schema (spec §14: "use Pydantic models"). Where a
stage already has one — TemplateDocument, ValidationResult, JobStatus —
routes return that directly instead of a duplicate API-only shape.
"""

from __future__ import annotations

from pydantic import BaseModel


class TemplateSummary(BaseModel):
    template_id: str
    template_version: str
    page_count: int
    character_count: int


class CreateJobRequest(BaseModel):
    template_id: str = "template_v1"


class ProcessJobRequest(BaseModel):
    family_name: str = "PersonalFont"
    creator: str = "PersonalFont"
    version: str = "1.0"
    description: str = "A personalized handwriting font generated by PersonalFont."


class UploadPagesResponse(BaseModel):
    job_id: str
    pages_uploaded: int
    filenames: list[str]


class RewriteCharacter(BaseModel):
    character_id: str
    character: str


class RewriteListResponse(BaseModel):
    job_id: str
    characters: list[RewriteCharacter]


class ExcludeRequest(BaseModel):
    character_ids: list[str]
